---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-mainnet-1-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-mainnet-1
spec:
  type: ClusterIP
  ports:
    - port: 12017
      protocol: UDP
      targetPort: 12017
      name: port-12017
    - port: 13017
      protocol: TCP
      targetPort: 13017
      name: port-13017
    - port: 15017
      protocol: TCP
      targetPort: 15017
      name: port-15017
    - port: 16017
      protocol: TCP
      targetPort: 16017
      name: port-16017
  selector:
    app: ssv-node-mainnet-1
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-mainnet-1
  name: ssv-node-mainnet-1
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-mainnet-1
  template:
    metadata:
      labels:
        app: ssv-node-mainnet-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5a.4xlarge
      containers:
      - name: ssv-node-mainnet-1
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12017
          name: port-12017
          hostPort: 12017
          protocol: UDP
        - containerPort: 13017
          name: port-13017
          hostPort: 13017
        - containerPort: 15017
          name: port-15017
          hostPort: 15017
        - containerPort: 16017
          name: port-16017
          hostPort: 16017
        env:
          - name: SHARE_CONFIG
            value: "./data1/share.yaml"
          - name: LOG_LEVEL
            value: "debug"
          - name: DB_REPORTING
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: NETWORK
            value: "mainnet"
          - name: CONSENSUS_TYPE
            value: "validation"
          - name: HOST_DNS
            value: ""
          - name: HOST_ADDRESS
            value: ""
          - name: DB_PATH
            value: "./data/db-mainnet--alan-09-2024"
          - name: METRICS_API_PORT
            value: "15017"
          - name: SSV_API_PORT
            value: "16017"
          - name: ENABLE_PROFILE
            value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-mainnet-1
        - mountPath: /data1/share.yaml
          subPath: share.yaml
          name: ssv-node-mainnet-1-cm
      volumes:
      - name: ssv-node-mainnet-1
        persistentVolumeClaim:
          claimName: ssv-node-mainnet-1
      - name: ssv-node-mainnet-1-cm
        configMap:
          name: ssv-node-mainnet-1-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
