name: E2E Test

on:
  workflow_dispatch:
    inputs:
      node_group_1_image_tag:
        type: string
        required: true
        description: "Image tag for the first group of nodes. Can be used for production, staging, or temporary environments. Example: v1.2.3-prod"


  pull_request:
    branches:
      - stage

  workflow_run:
    workflows: ["Lint", "Unit tests"]
    types: [completed]
    branches: [stage, main]


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run e2e.sh
        env:
          BEACON_NODE_URL: ${{ secrets.E2E_BEACON_NODE_URL }}
#          CLEAN_SERVICES: true
          EXECUTION_NODE_URL: ${{ secrets.E2E_EXECUTION_NODE_URL }}
          NODE_GROUP_1_IMAGE_TAG: ${{ github.event.inputs.node_group_1_image_tag }}
        run: |
          cd ./e2e/
          chmod +x ./run.sh
          ./run.sh

      - name: clean up
        run: docker compose down -v

      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: './logs'
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz

      - name: Cleanup
        if: always()
        run: docker compose down -v